function point(id, description, owner) {
  return Object.freeze({ id, description, owner });
}

/**
 * 修改点 ID 只表达稳定业务语义；官方版本、压缩变量名和具体选择器必须留在 Locator 中。
 * 目录集中声明可以阻止不同子系统为同一兼容边界创造近似但不一致的 ID。
 */
const POINT_DEFINITIONS = Object.freeze([
  point("web.runtime.platform.desktop-globals", "补齐官方 Renderer 依赖的桌面全局对象", "web-shell"),
  point("web.runtime.bridge.desktop-api", "代理官方桌面 Bridge API", "web-shell"),
  point("web.runtime.bridge.ipc-transport", "把 Renderer IPC 转换为 Gateway HTTP 或 WebSocket", "web-shell"),
  point("web.runtime.bridge.app-host-port", "把浏览器 MessagePort 接入官方 app-host", "web-shell"),
  point("web.runtime.bridge.persisted-atom", "同步官方 persisted atom", "web-shell"),
  point("web.runtime.bridge.shared-object", "模拟官方 shared-object 快照和订阅", "web-shell"),
  point("web.runtime.bridge.initial-sidebar", "暴露初始侧栏快照", "web-shell"),
  point("web.runtime.bridge.feature-gates", "注入 Web 环境所需桌面能力开关", "web-shell"),
  point("web.runtime.network.statsig", "本地响应 Statsig 初始化请求", "web-shell"),
  point("web.runtime.network.telemetry", "阻止隐藏 Web 环境发送无效遥测", "web-shell"),
  point("web.runtime.protocol.connector-logo", "合并 connector logo IPC 请求", "web-shell"),
  point("web.runtime.dom.webview-shim", "使用 iframe 模拟 Electron webview", "web-shell"),
  point("web.runtime.native.file-picker", "把 Electron 文件选择转换为浏览器文件选择", "web-shell"),
  point("web.runtime.native.ide-context", "为 Web 环境合成 IDE context", "web-shell"),
  point("web.runtime.native.notification", "把 Gateway 通知映射为浏览器 Notification", "web-shell"),
  point("web.runtime.native.terminal", "有序转发官方终端消息", "web-shell"),
  point("web.runtime.native.external-open", "把桌面打开行为转换为浏览器行为", "web-shell"),
  point("web.runtime.dom.app-fs-image", "改写官方 app 文件图片地址", "web-shell"),
  point("web.runtime.dom.gateway-auth-menu", "向官方账号菜单插入 Gateway 退出入口", "web-shell"),
  point("web.runtime.workspace.root-picker", "接管远端项目和会话的目录选择", "web-shell"),
  point("web.runtime.dom.remote-file-menu", "向官方文件树菜单注入远端下载", "web-shell"),
  point("web.runtime.dom.sidebar-preview-handoff", "把预渲染侧栏交接给官方侧栏", "web-shell"),
  point("web.runtime.dom.late-module-preload", "延迟加载非首屏官方模块", "web-shell"),
  point("web.runtime.dom.offscreen-animation", "暂停离屏官方动画", "web-shell"),
  point("web.runtime.dom.tooltip-dismiss", "适配官方 Tooltip 挂载和关闭", "web-shell"),
  point("web.runtime.dom.window-controls-overlay", "适配 PWA 标题栏和安全区", "web-shell"),
  point("web.runtime.smart-router.composer", "定位并适配官方模型选择器", "smart-router"),
  point("web.runtime.smart-router.settings", "向官方设置注入智能调度页面", "smart-router"),
  point("web.runtime.smart-router.summary", "在官方线程界面展示调度结果", "smart-router"),
  point("web.runtime.plugin.project-recent-sort", "调整项目和会话最近使用排序", "web-plugins"),
  point("web.runtime.protocol.token-usage", "从官方协议提取线程 Token 用量", "web-shell"),
  point("web.runtime.dom.token-usage-inline", "在官方消息操作区插入 Token 用量", "web-plugins"),
  point("web.runtime.plugin.mobile-sidebar", "移动端新会话后自动收起侧栏", "web-plugins"),
  point("web.runtime.plugin.mobile-keyboard", "修正移动端发送后的键盘行为", "web-plugins"),
  point("web.runtime.plugin.ios-layout", "修正 iOS 视口和键盘避让", "web-plugins"),
  point("web.runtime.shell.legacy-document-replace", "兼容旧登录壳替换官方文档", "web-shell"),

  point("gateway.runtime.environment.official-app", "把 Gateway 环境对齐到官方桌面应用", "official-runtime"),
  point("gateway.runtime.environment.no-asar", "允许隐藏 Runtime 访问抽取目录", "official-runtime"),
  point("gateway.runtime.chromium.hidden-services", "关闭隐藏 Runtime 无效后台服务", "official-runtime"),
  point("gateway.runtime.chromium.gcm-profile", "隔离隐藏 Runtime 的 GCM Profile", "official-runtime"),
  point("gateway.runtime.node.electron-module-loader", "包装官方 electron 模块导出", "official-runtime"),
  point("gateway.runtime.electron.notification", "替换官方 Notification", "official-runtime"),
  point("gateway.runtime.electron.tray", "替换官方 Tray", "official-runtime"),
  point("gateway.runtime.electron.ipc-main", "捕获官方 ipcMain 注册", "official-runtime"),
  point("gateway.runtime.electron.ipc-event", "构造兼容的 Electron IPC 事件", "official-runtime"),
  point("gateway.runtime.electron.browser-window", "隐藏官方 BrowserWindow", "official-runtime"),
  point("gateway.runtime.electron.web-contents-send", "把官方 webContents 消息转发到浏览器", "official-runtime"),
  point("gateway.runtime.electron.dialog-open", "接管隐藏窗口目录选择", "official-runtime"),
  point("gateway.runtime.electron.shell-open", "接管官方文件和外部地址打开行为", "official-runtime"),
  point("gateway.runtime.electron.single-instance", "允许 Gateway 与官方桌面端并存", "official-runtime"),
  point("gateway.runtime.electron.quit-dialog", "抑制隐藏 Runtime 退出确认框", "official-runtime"),
  point("gateway.runtime.electron.dock-visibility", "保持隐藏 Runtime 不出现在 Dock", "official-runtime"),
  point("gateway.runtime.process.app-server-launch", "重定向官方 App Server 可执行文件", "official-runtime"),
  point("gateway.runtime.process.remote-file-manager", "把系统文件管理器命令转换为远端下载", "official-runtime"),
  point("gateway.runtime.process.computer-use-installer", "兼容 Computer Use Installer 执行合约", "official-runtime"),
  point("gateway.runtime.app-server.transport", "建立 App Server NDJSON 中间层", "smart-router"),
  point("gateway.runtime.app-server.virtual-model", "向官方协议注入 Auto 模型", "smart-router"),
  point("gateway.runtime.app-server.turn-router", "替换 turn/start 的真实模型和强度", "smart-router"),
  point("gateway.runtime.app-server.internal-session", "隔离智能分类内部会话", "smart-router"),
  point("gateway.runtime.app-server.route-metadata", "向官方通知注入调度元数据", "smart-router"),
  point("gateway.runtime.app-server.history-context", "维护智能分类的有界历史上下文", "smart-router"),
  point("gateway.runtime.app-host.relay", "中继浏览器与官方 app-host", "official-runtime"),
  point("gateway.runtime.ipc.request-route", "按请求和客户端定向官方 IPC 响应", "official-runtime"),
  point("gateway.runtime.ipc.chunked-message", "重组官方分块 IPC 并确认", "official-runtime"),
  point("gateway.runtime.ipc.app-catalog-compaction", "压缩 Web 侧应用和插件目录", "official-runtime"),
  point("gateway.runtime.ipc.hidden-renderer-suppression", "避免隐藏 Renderer 重复消费代理消息", "official-runtime"),
  point("gateway.runtime.ipc.initial-sidebar-bootstrap", "读取并缓存官方初始侧栏快照", "official-runtime"),
  point("gateway.runtime.ipc.thread-list-invalidation", "补发最近会话缓存失效", "official-runtime"),
  point("gateway.runtime.ipc.live-observer", "观察官方 Desktop 本地实时协议", "official-runtime"),
  point("gateway.runtime.ipc.workspace-context", "从官方 IPC 提取工作区上下文", "official-runtime"),
  point("gateway.runtime.ipc.open-file-context", "把官方打开文件转换为浏览器预览", "official-runtime"),
  point("gateway.runtime.ipc.computer-use-auth", "短路已满足目标的 Computer Use 安装操作", "official-runtime"),

  point("static.cache.main.native-pet.factory", "禁用隐藏 Runtime 的 Native Pet 工厂", "official-cache"),
  point("static.cache.main.native-pet.prewarm", "跳过隐藏 Native Pet 预热", "official-cache"),
  point("static.cache.main.native-pet.restore", "阻止隐藏 Profile 恢复 Native Pet", "official-cache"),
  point("static.cache.main.macos-push-registration", "跳过隐藏 Runtime 的 macOS Push 注册", "official-cache"),
  point("static.cache.main.git-origin-resolver", "合并侧栏 Git Origin 探测", "official-cache"),
  point("static.cache.main.git-local-prefilter", "在 Git 探测前执行本地仓库预检", "official-cache"),
  point("static.cache.main.git-background-command", "限制并缓存后台 Git 命令", "official-cache"),
  point("static.cache.main.worktree-shell-environment", "限制并缓存 Worktree Shell 环境请求", "official-cache"),
  point("static.cache.renderer.html.lang", "改写官方 HTML 语言", "renderer-cache"),
  point("static.cache.renderer.html.viewport", "改写官方移动端 viewport", "renderer-cache"),
  point("static.cache.renderer.html.icon-pwa", "注入 Web 和 PWA 图标", "renderer-cache"),
  point("static.cache.renderer.html.asset-path-map", "映射官方静态资源路径", "renderer-cache"),
  point("static.cache.renderer.html.font-preload", "移除无法复用的字体预载", "renderer-cache"),
  point("static.cache.renderer.html.runtime-bootstrap", "注入 OpenCodex Web 运行时", "renderer-cache"),
  point("static.cache.renderer.html.startup-preload", "注入首屏静态资源预载", "renderer-cache"),
  point("static.cache.renderer.html.sidebar-preview", "注入首屏侧栏预览", "renderer-cache"),
  point("static.cache.renderer.html.loading-animation", "限制官方加载动画耗电", "renderer-cache"),
  point("static.cache.renderer.asset-namespace", "隔离修改后的官方资源缓存命名空间", "renderer-cache"),
  point("static.cache.renderer.csp.unsafe-eval", "允许官方 Web 运行时所需 unsafe-eval", "renderer-cache"),
  point("static.cache.renderer.csp.manifest-src", "允许同源 PWA Manifest", "renderer-cache"),
  point("static.cache.renderer.history-turn-signals", "补齐历史会话 Turn 信号", "renderer-cache"),
  point("static.cache.renderer.application-menu", "适配 Web 环境 Application Menu 能力", "renderer-cache"),
  point("static.cache.renderer.app-server-request-scheduling", "调整 App Server 后台请求调度", "renderer-cache"),
  point("static.cache.renderer.plugin-image-lazy-load", "延迟加载插件图片", "renderer-cache"),
  point("static.cache.renderer.open-in-folder-locale", "把打开文件夹文案改为远端下载", "renderer-cache"),
  point("static.cache.runner.macos-background-bundle", "生成 macOS 后台 Runner Bundle", "runner-cache"),
  point("static.cache.runner.macos-entry-signature", "签名 macOS Runner 入口副本", "runner-cache"),
  point("static.cache.runner.portable-layout", "构建 Windows 和 Linux Runner 布局", "runner-cache"),
  point("static.cache.runner.gateway-asar", "生成 OpenCodex Runner app.asar", "runner-cache"),
  point("static.cache.runner.windows-asar-integrity", "修正 Windows Runner ASAR 完整性资源", "runner-cache"),
]);

const FEATURE_DEFINITIONS = Object.freeze([
  Object.freeze({
    id: "feature.startup-history",
    description: "首屏、历史会话和侧栏同步",
    fallback: "回退到官方侧栏和按需加载",
    required: Object.freeze([
      "static.cache.renderer.html.startup-preload",
      "gateway.runtime.ipc.initial-sidebar-bootstrap",
      "gateway.runtime.ipc.thread-list-invalidation",
      "web.runtime.dom.sidebar-preview-handoff",
    ]),
    optional: Object.freeze([
      "gateway.runtime.ipc.live-observer",
      "static.cache.renderer.html.sidebar-preview",
      "static.cache.renderer.history-turn-signals",
    ]),
  }),
  Object.freeze({
    id: "feature.workspace-creation",
    description: "新项目和新工作树创建",
    fallback: "回退到官方目录选择和 Shell 环境读取",
    required: Object.freeze([
      "web.runtime.workspace.root-picker",
      "web.runtime.bridge.feature-gates",
      "gateway.runtime.ipc.workspace-context",
      "static.cache.main.worktree-shell-environment",
    ]),
    optional: Object.freeze([]),
  }),
  Object.freeze({
    id: "feature.remote-files",
    description: "远端文件预览和下载",
    fallback: "保留官方本机打开行为",
    required: Object.freeze([
      "web.runtime.dom.remote-file-menu",
      "gateway.runtime.process.remote-file-manager",
      "gateway.runtime.ipc.open-file-context",
    ]),
    optional: Object.freeze([
      "gateway.runtime.electron.shell-open",
      "static.cache.renderer.open-in-folder-locale",
    ]),
  }),
  Object.freeze({
    id: "feature.smart-routing",
    description: "Auto 模型智能调度",
    fallback: "回退到用户显式选择的官方模型",
    required: Object.freeze([
      "gateway.runtime.app-server.transport",
      "gateway.runtime.app-server.virtual-model",
      "gateway.runtime.app-server.turn-router",
      "web.runtime.smart-router.composer",
      "web.runtime.smart-router.settings",
      "web.runtime.smart-router.summary",
    ]),
    optional: Object.freeze([
      "gateway.runtime.app-server.internal-session",
      "gateway.runtime.app-server.route-metadata",
      "gateway.runtime.app-server.history-context",
    ]),
  }),
  Object.freeze({
    id: "feature.notification-power",
    description: "通知和隐藏 Runtime 后台节能",
    fallback: "保留官方逻辑或关闭远端通知",
    required: Object.freeze([
      "gateway.runtime.electron.notification",
      "web.runtime.native.notification",
    ]),
    optional: Object.freeze([
      "static.cache.main.native-pet.factory",
      "static.cache.main.native-pet.prewarm",
      "static.cache.main.native-pet.restore",
      "static.cache.main.macos-push-registration",
      "gateway.runtime.electron.tray",
      "gateway.runtime.chromium.gcm-profile",
    ]),
  }),
  Object.freeze({
    id: "feature.renderer-core-bridge",
    description: "官方 Renderer 与 Gateway 核心桥",
    fallback: "核心桥不可用时停止提供远程 Renderer",
    required: Object.freeze([
      "static.cache.renderer.html.runtime-bootstrap",
      "web.runtime.bridge.desktop-api",
      "web.runtime.bridge.ipc-transport",
      "gateway.runtime.electron.ipc-main",
      "gateway.runtime.electron.web-contents-send",
      "gateway.runtime.app-host.relay",
    ]),
    optional: Object.freeze([]),
  }),
]);

function registerCompatibilityCatalog(registry) {
  registry.registerPoints(POINT_DEFINITIONS);
  registry.registerFeatures(FEATURE_DEFINITIONS);
  return registry;
}

module.exports = {
  FEATURE_DEFINITIONS,
  POINT_DEFINITIONS,
  registerCompatibilityCatalog,
};
